name: Kablo EPG Bot

on:
  schedule:
    - cron: '0 */3 * * *' # Her 3 saatte bir (UTC)
  workflow_dispatch:

jobs:
  run-epg-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run projekablo.py
        run: python projekablo.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Kablo EPG Bot"
          git config --global user.email "epg-bot@users.noreply.github.com"
          git add kabloepg.xml
          git commit -m "Güncel EPG XML [bot]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
