name: M3U Güncelle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  m3u-guncelle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download kabloepg.xml
        run: wget https://github.com/ingtv/tvingdd/blob/main/kabloepg.xml -O kabloepg.xml

      - name: Download mehmet.m3u
        run: wget https://github.com/ingtv/tvingdd/blob/main/mehmet_guncel.m3u -O mehmet.m3u

      - name: Run M3U Güncelleme Scripti
        run: python guncelle_m3u.py

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"
          git add mehmet_guncel.m3u
          git commit -m "Otomatik m3u güncellendi [bot]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
